from sqlalchemy import inspect, text

from app.core.config import settings


def ensure_runtime_columns(engine):
    inspector = inspect(engine)
    user_columns = {column["name"] for column in inspector.get_columns("users")}
    room_columns = {column["name"] for column in inspector.get_columns("rooms")}
    table_names = set(inspector.get_table_names())

    with engine.begin() as connection:
        dialect = connection.dialect.name
        timestamp_type = "TIMESTAMP WITH TIME ZONE" if dialect == "postgresql" else "DATETIME"

        if "last_login_at" not in user_columns:
            connection.execute(text(f"ALTER TABLE users ADD COLUMN last_login_at {timestamp_type}"))

        if "login_count" not in user_columns:
            connection.execute(text("ALTER TABLE users ADD COLUMN login_count INTEGER NOT NULL DEFAULT 0"))

        if "email_verified" not in user_columns:
            verified_default = "TRUE" if dialect == "postgresql" else "1"
            connection.execute(
                text(f"ALTER TABLE users ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT {verified_default}")
            )

        if "role" not in user_columns:
            connection.execute(text("ALTER TABLE users ADD COLUMN role VARCHAR(20) NOT NULL DEFAULT 'user'"))
            if settings.ADMIN_USERNAME:
                connection.execute(
                    text("UPDATE users SET role = 'admin' WHERE LOWER(username) = LOWER(:username)"),
                    {"username": settings.ADMIN_USERNAME},
                )
            for username in settings.TESTER_USERNAMES:
                connection.execute(
                    text(
                        "UPDATE users SET role = 'tester' "
                        "WHERE LOWER(username) = LOWER(:username) AND role = 'user'"
                    ),
                    {"username": username},
                )

        connection.execute(
            text("UPDATE users SET role = 'admin' WHERE LOWER(username) = LOWER(:username)"),
            {"username": settings.SUPER_ADMIN_USERNAME},
        )

        if "last_seen_at" not in user_columns:
            connection.execute(text(f"ALTER TABLE users ADD COLUMN last_seen_at {timestamp_type}"))

        if "avatar_id" not in user_columns:
            connection.execute(text("ALTER TABLE users ADD COLUMN avatar_id VARCHAR(32) NOT NULL DEFAULT 'arcade-green'"))

        if "system" not in room_columns:
            connection.execute(text("ALTER TABLE rooms ADD COLUMN system VARCHAR(32) NOT NULL DEFAULT 'cpc'"))

        if "party_max_players" not in room_columns:
            connection.execute(text("ALTER TABLE rooms ADD COLUMN party_max_players INTEGER NOT NULL DEFAULT 2"))

        if "current_game" not in room_columns:
            connection.execute(text("ALTER TABLE rooms ADD COLUMN current_game VARCHAR(512)"))

        if "feedback_items" in table_names:
            connection.execute(text("UPDATE feedback_items SET status = 'unstarted' WHERE status = 'open'"))
            connection.execute(text("UPDATE feedback_items SET status = 'in_review' WHERE status = 'reviewing'"))
            connection.execute(text("UPDATE feedback_items SET status = 'resolved' WHERE status = 'done'"))

        bool_type = "BOOLEAN" if dialect == "postgresql" else "BOOLEAN"
        false_default = "FALSE" if dialect == "postgresql" else "0"
        true_default = "TRUE" if dialect == "postgresql" else "1"

        if "tournaments" in table_names:
            tournament_columns = {column["name"] for column in inspector.get_columns("tournaments")}
            if "is_public" not in tournament_columns:
                connection.execute(text(
                    f"ALTER TABLE tournaments ADD COLUMN is_public {bool_type} NOT NULL DEFAULT {true_default}"
                ))

        if "mame_leaderboard_games" not in table_names:
            id_column = "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if dialect == "postgresql" else "id INTEGER PRIMARY KEY"
            connection.execute(text(
                "CREATE TABLE mame_leaderboard_games ("
                f"{id_column}, "
                "rom_name VARCHAR(64) NOT NULL UNIQUE, "
                "display_name VARCHAR(255) NOT NULL, "
                f"leaderboard_supported {bool_type} NOT NULL DEFAULT {false_default}, "
                "score_source VARCHAR(16) NOT NULL DEFAULT 'unsupported', "
                "parser VARCHAR(32) NOT NULL DEFAULT 'unsupported', "
                f"enabled {bool_type} NOT NULL DEFAULT {false_default}, "
                f"created_at {timestamp_type} DEFAULT CURRENT_TIMESTAMP NOT NULL"
                ")"
            ))
            connection.execute(text("CREATE INDEX ix_mame_leaderboard_games_rom_name ON mame_leaderboard_games (rom_name)"))
        else:
            mame_game_columns = {column["name"] for column in inspector.get_columns("mame_leaderboard_games")}
            if "display_name" not in mame_game_columns:
                connection.execute(text("ALTER TABLE mame_leaderboard_games ADD COLUMN display_name VARCHAR(255) NOT NULL DEFAULT ''"))
            if "leaderboard_supported" not in mame_game_columns:
                connection.execute(text(
                    f"ALTER TABLE mame_leaderboard_games ADD COLUMN leaderboard_supported {bool_type} NOT NULL DEFAULT {false_default}"
                ))
            if "score_source" not in mame_game_columns:
                connection.execute(text("ALTER TABLE mame_leaderboard_games ADD COLUMN score_source VARCHAR(16) NOT NULL DEFAULT 'unsupported'"))
            if "parser" not in mame_game_columns:
                connection.execute(text("ALTER TABLE mame_leaderboard_games ADD COLUMN parser VARCHAR(32) NOT NULL DEFAULT 'unsupported'"))
            if "enabled" not in mame_game_columns:
                connection.execute(text(
                    f"ALTER TABLE mame_leaderboard_games ADD COLUMN enabled {bool_type} NOT NULL DEFAULT {false_default}"
                ))
            if "created_at" not in mame_game_columns:
                connection.execute(text(
                    f"ALTER TABLE mame_leaderboard_games ADD COLUMN created_at {timestamp_type} DEFAULT CURRENT_TIMESTAMP NOT NULL"
                ))

        if "mame_high_scores" not in table_names:
            id_column = "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if dialect == "postgresql" else "id INTEGER PRIMARY KEY"
            connection.execute(text(
                "CREATE TABLE mame_high_scores ("
                f"{id_column}, "
                "user_id INTEGER NOT NULL, "
                "rom_name VARCHAR(64) NOT NULL, "
                "score INTEGER NOT NULL, "
                "initials VARCHAR(16), "
                "rank_in_game INTEGER, "
                "session_id VARCHAR(128) NOT NULL, "
                "source_path VARCHAR(512), "
                "parser VARCHAR(32) NOT NULL, "
                f"created_at {timestamp_type} DEFAULT CURRENT_TIMESTAMP NOT NULL, "
                "FOREIGN KEY(user_id) REFERENCES users (id), "
                "CONSTRAINT uq_mame_high_score_user_rom UNIQUE "
                "(user_id, rom_name)"
                ")"
            ))
            connection.execute(text("CREATE INDEX ix_mame_high_scores_user_id ON mame_high_scores (user_id)"))
            connection.execute(text("CREATE INDEX ix_mame_high_scores_rom_name ON mame_high_scores (rom_name)"))
            connection.execute(text("CREATE INDEX ix_mame_high_scores_score ON mame_high_scores (score)"))
            connection.execute(text("CREATE INDEX ix_mame_high_scores_session_id ON mame_high_scores (session_id)"))
            connection.execute(text("CREATE INDEX ix_mame_high_scores_created_at ON mame_high_scores (created_at)"))
        else:
            mame_score_columns = {column["name"] for column in inspector.get_columns("mame_high_scores")}
            if "user_id" not in mame_score_columns:
                connection.execute(text("ALTER TABLE mame_high_scores ADD COLUMN user_id INTEGER"))
            if "rom_name" not in mame_score_columns:
                connection.execute(text("ALTER TABLE mame_high_scores ADD COLUMN rom_name VARCHAR(64) NOT NULL DEFAULT ''"))
            if "score" not in mame_score_columns:
                connection.execute(text("ALTER TABLE mame_high_scores ADD COLUMN score INTEGER NOT NULL DEFAULT 0"))
            if "initials" not in mame_score_columns:
                connection.execute(text("ALTER TABLE mame_high_scores ADD COLUMN initials VARCHAR(16)"))
            if "rank_in_game" not in mame_score_columns:
                connection.execute(text("ALTER TABLE mame_high_scores ADD COLUMN rank_in_game INTEGER"))
            if "session_id" not in mame_score_columns:
                connection.execute(text("ALTER TABLE mame_high_scores ADD COLUMN session_id VARCHAR(128) NOT NULL DEFAULT ''"))
            if "source_path" not in mame_score_columns:
                connection.execute(text("ALTER TABLE mame_high_scores ADD COLUMN source_path VARCHAR(512)"))
            if "parser" not in mame_score_columns:
                connection.execute(text("ALTER TABLE mame_high_scores ADD COLUMN parser VARCHAR(32) NOT NULL DEFAULT 'unsupported'"))
            if "created_at" not in mame_score_columns:
                connection.execute(text(
                    f"ALTER TABLE mame_high_scores ADD COLUMN created_at {timestamp_type} DEFAULT CURRENT_TIMESTAMP NOT NULL"
                ))

        if "amiga_high_scores" not in table_names:
            id_column = "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if dialect == "postgresql" else "id INTEGER PRIMARY KEY"
            connection.execute(text(
                "CREATE TABLE amiga_high_scores ("
                f"{id_column}, "
                "user_id INTEGER NOT NULL, "
                "game_key VARCHAR(64) NOT NULL, "
                "score INTEGER NOT NULL, "
                "initials VARCHAR(16), "
                "session_id VARCHAR(128) NOT NULL, "
                "source_path VARCHAR(512), "
                "parser VARCHAR(64) NOT NULL, "
                f"created_at {timestamp_type} DEFAULT CURRENT_TIMESTAMP NOT NULL, "
                "FOREIGN KEY(user_id) REFERENCES users (id), "
                "CONSTRAINT uq_amiga_high_score_user_game UNIQUE (user_id, game_key)"
                ")"
            ))
            connection.execute(text("CREATE INDEX ix_amiga_high_scores_user_id ON amiga_high_scores (user_id)"))
            connection.execute(text("CREATE INDEX ix_amiga_high_scores_game_key ON amiga_high_scores (game_key)"))
            connection.execute(text("CREATE INDEX ix_amiga_high_scores_score ON amiga_high_scores (score)"))
            connection.execute(text("CREATE INDEX ix_amiga_high_scores_session_id ON amiga_high_scores (session_id)"))
            connection.execute(text("CREATE INDEX ix_amiga_high_scores_created_at ON amiga_high_scores (created_at)"))

        # Remove a development-only Donkey Kong score without affecting any
        # legitimate score the same user may achieve after this cleanup.
        connection.execute(
            text(
                "DELETE FROM mame_high_scores "
                "WHERE rom_name = 'dkong' "
                "AND score = 765000 "
                "AND created_at < :cutoff "
                "AND user_id IN ("
                "SELECT id FROM users WHERE LOWER(username) = LOWER(:username)"
                ")"
            ),
            {
                "cutoff": "2026-07-30 00:00:00+00:00",
                "username": "OldStyleGaming",
            },
        )

        # The former Donkey Kong parser scanned every three-byte window in the
        # .hi file and misread non-score row data as 900,000 for this account.
        # Correct the confirmed personal best while deploying the fixed parser.
        connection.execute(
            text(
                "UPDATE mame_high_scores SET score = 49000 "
                "WHERE rom_name = 'dkong' "
                "AND score = 900000 "
                "AND user_id IN ("
                "SELECT id FROM users WHERE LOWER(username) = LOWER(:username)"
                ")"
            ),
            {"username": "OldStyleGaming"},
        )
